
export const metadata = {
title:{
  default:'Learning Next',
  template:'%s | My App',
},
  description: 'Generated by Next.js',
}

import './app.css'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
